/**
 * Nova Verify - Contract Configuration
 * 
 * Reads deployment info from deploy-info.json (generated by deploy-testnet.js)
 * and falls back to environment variables.
 */

export interface DeployInfo {
  network: string;
  contractId?: string;
  adminPublicKey: string;
  adminSecretKey?: string;
  wasmHash?: string;
  uploadTx?: string;
  createTx?: string;
  deployedAt?: string;
}

export interface ContractConfig {
  /** The deployed contract address/ID on Stellar */
  contractId: string;
  /** Admin public key (Stellar address starting with G) */
  adminPublicKey: string;
  /** Network the contract is deployed on */
  network: 'testnet' | 'mainnet' | 'futurenet';
  /** Soroban RPC URL */
  rpcUrl: string;
  /** Stellar Horizon URL */
  horizonUrl: string;
  /** SHA-256 hash of the deployed WASM */
  wasmHash?: string;
  /** Is the contract configured and ready? */
  isConfigured: boolean;
}

function getNetworkConfig(network: string) {
  switch (network) {
    case 'mainnet':
      return {
        rpcUrl: 'https://soroban.stellar.org',
        horizonUrl: 'https://horizon.stellar.org',
        networkPassphrase: 'Public Global Stellar Network ; September 2015',
      };
    case 'futurenet':
      return {
        rpcUrl: 'https://rpc-futurenet.stellar.org',
        horizonUrl: 'https://horizon-futurenet.stellar.org',
        networkPassphrase: 'Test SDF Future Network ; October 2022',
      };
    case 'testnet':
    default:
      return {
        rpcUrl: 'https://soroban-testnet.stellar.org',
        horizonUrl: 'https://horizon-testnet.stellar.org',
        networkPassphrase: 'Test SDF Network ; September 2015',
      };
  }
}

/**
 * Load deployment info from the deploy-info.json file.
 * In production, this would be bundled at build time or fetched from an API.
 */
async function loadDeployInfo(): Promise<DeployInfo | null> {
  try {
    const response = await fetch('/deploy-info.json');
    if (response.ok) {
      return await response.json();
    }
  } catch {
    // deploy-info.json not available (dev mode or not deployed yet)
  }
  return null;
}

let cachedConfig: ContractConfig | null = null;

/**
 * Get the contract configuration.
 * Caches the result after first load.
 */
export async function getContractConfig(): Promise<ContractConfig> {
  if (cachedConfig) return cachedConfig;

  // Try loading deploy-info.json first
  const deployInfo = await loadDeployInfo();

  const contractId = deployInfo?.contractId
    || process.env.REACT_APP_CONTRACT_ID
    || '';

  const adminPublicKey = deployInfo?.adminPublicKey
    || process.env.REACT_APP_ADMIN_PUBLIC_KEY
    || '';

  const network = (deployInfo?.network
    || process.env.REACT_APP_STELLAR_NETWORK
    || 'testnet') as 'testnet' | 'mainnet' | 'futurenet';

  const networkConfig = getNetworkConfig(network);

  cachedConfig = {
    contractId,
    adminPublicKey,
    network,
    rpcUrl: process.env.REACT_APP_SOROBAN_RPC_URL || networkConfig.rpcUrl,
    horizonUrl: process.env.REACT_APP_HORIZON_URL || networkConfig.horizonUrl,
    wasmHash: deployInfo?.wasmHash || process.env.REACT_APP_WASM_HASH,
    isConfigured: !!contractId && !!adminPublicKey,
  };

  if (!cachedConfig.isConfigured) {
    console.warn(
      '[Nova Verify] Contract not configured. Run deploy-testnet.js to deploy, then place deploy-info.json in the frontend public folder.'
    );
  }

  return cachedConfig;
}

/**
 * Synchronous accessor for when you already know the config is loaded.
 * Returns null if not yet configured.
 */
export function getContractConfigSync(): ContractConfig | null {
  return cachedConfig;
}

export default getContractConfig;
